### ISSUE TITLE
Weird issue can happen when using multiple components

### ISSUE THREAD

**Issue by pbellon** [fazouane-marouane/remark-jsx#12]
Well, I'm not exactly sure why this happens but in our "skoli-app-template" project we've come across parsing errors when heavily using components in markdown (for notes in our case). I've had some trouble to reproduce the issue outside the project but I've finally found a reproducible example with (supposedly) valid markdown with components that were producing error:
```md 
# Test

Pof <MyComponent attr="test">pof</MyComponent>

Ok <MyComponent>with content</MyComponent> inside paragraph <Autoclose test="ok"/>

> It should also work inside <MyComponent other="ok">blockquotes</MyComponent>

But it should also work with a mix of <MyComponent text="custom components">custom components</MyComponent> <Test>another</Test> <Test>another</Test> but we can continue and maybe it will break <MyComponent test="pof pof">here ?</MyComponent> let's continue until it break <Test>is it breaking ?</Test>.

Let's try to continue
```
With the following configuration:
```js
var parser = unified()
  .use(parse)
  .use(customElementCompiler, {
    componentWhitelist: [
      'MyComponent',
      'Autoclose',
      'Test',
    ]});
```
Will throw an error when parsing:
```
Error
        at tokens.reduce.type (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/smart-html-parser.js:128:19)
        at Array.reduce (<anonymous>)
        at parse (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/smart-html-parser.js:121:23)
        at Of.<anonymous> (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/custom-element-parser.js:24:18)
        at Of.tokenize [as tokenizeBlock] (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/node_modules/remark-parse/lib/tokenizer.js:103:18)
        at Of.parse (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/node_modules/remark-parse/lib/parse.js:33:20)
        at Function.parse (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/node_modules/unified/index.js:275:45)
        at pipelineParse (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/node_modules/unified/index.js:22:16)
        at wrapped (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/node_modules/trough/index.js:93:19)
        at next (/home/trb/Dev/remark-jsx/packages/remark-custom-element-to-hast/node_modules/trough/index.js:56:24)
```

**Comment by pbellon** [comment]
I've no clue why it's breaking. If we remove the latest usage of the `Test` component it will be ok but as soon as we add it, it breaks parsing :(

**Comment by pbellon** [comment]
It seems the parser have some trouble to detected all opening tags for the various components types. Here's an output of the `tokens` that are handled in the `reduce` function of smart-html-parser:

**EDIT**: I think it may "just" be an ordering issue. It seems it breaks because we first encounter a `</Test>` in the reduce function where no corresponding opening tag were treated before. I'll try to sort those tokens by `startAt` to see if that resolve the issue.
```js
[
  {
    "type": "raw",
    "value": "Test",
    "startsAt": 0,
    "endsAt": 4
  }
]
```
and 
```js
[
  {
    "type": "raw",
    "value": "  Pof ",
    "startsAt": 0,
    "endsAt": 6
  },
  {
    "value": "<MyComponent attr=\"test\">",
    "type": "openTag",
    "tagName": "MyComponent",
    "startsAt": 6,
    "endsAt": 31,
    "properties": {
      "attr": "test"
    }
  },
  {
    "type": "raw",
    "value": "pof",
    "startsAt": 31,
    "endsAt": 34
  },
  {
    "value": "</MyComponent>",
    "type": "closingTag",
    "tagName": "MyComponent",
    "startsAt": 34,
    "endsAt": 48
  },
  {
    "type": "raw",
    "value": "\n\n  Ok ",
    "startsAt": 48,
    "endsAt": 55
  },
  {
    "value": "<MyComponent>",
    "type": "openTag",
    "tagName": "MyComponent",
    "startsAt": 55,
    "endsAt": 68,
    "properties": {}
  },
  {
    "type": "raw",
    "value": "with content",
    "startsAt": 68,
    "endsAt": 80
  },
  {
    "value": "</MyComponent>",
    "type": "closingTag",
    "tagName": "MyComponent",
    "startsAt": 202,
    "endsAt": 216
  },
  {
    "type": "raw",
    "value": " inside paragraph ",
    "startsAt": 94,
    "endsAt": 112
  },
  {
    "value": "<Autoclose test=\"ok\"/>",
    "type": "autoCloseTag",
    "tagName": "Autoclose",
    "startsAt": 112,
    "endsAt": 134,
    "properties": {
      "test": "ok"
    }
  },
  {
    "type": "raw",
    "value": "\n\n  > It should also work inside ",
    "startsAt": 134,
    "endsAt": 167
  },
  {
    "value": "<MyComponent other=\"ok\">",
    "type": "openTag",
    "tagName": "MyComponent",
    "startsAt": 167,
    "endsAt": 191,
    "properties": {
      "other": "ok"
    }
  },
  {
    "type": "raw",
    "value": "blockquotes",
    "startsAt": 191,
    "endsAt": 202
  },
  {
    "value": "</MyComponent>",
    "type": "closingTag",
    "tagName": "MyComponent",
    "startsAt": 80,
    "endsAt": 94
  },
  {
    "type": "raw",
    "value": "\n  \n  But it should also work with a mix of ",
    "startsAt": 216,
    "endsAt": 260
  },
  {
    "value": "<MyComponent text=\"custom components\">",
    "type": "openTag",
    "tagName": "MyComponent",
    "startsAt": 260,
    "endsAt": 298,
    "properties": {
      "text": "custom components"
    }
  },
  {
    "type": "raw",
    "value": "custom components",
    "startsAt": 298,
    "endsAt": 315
  },
  {
    "value": "</MyComponent>",
    "type": "closingTag",
    "tagName": "MyComponent",
    "startsAt": 450,
    "endsAt": 464
  },
  {
    "value": "</Test>",
    "type": "closingTag",
    "tagName": "Test",
    "startsAt": 364,
    "endsAt": 371
  },
  {
    "value": "</MyComponent>",
    "type": "closingTag",
    "tagName": "MyComponent",
    "startsAt": 315,
    "endsAt": 329
  },
  {
    "value": "</Test>",
    "type": "closingTag",
    "tagName": "Test",
    "startsAt": 343,
    "endsAt": 350
  },
  {
    "type": "raw",
    "value": " but we can continue and maybe it will break ",
    "startsAt": 371,
    "endsAt": 416
  },
  {
    "value": "<MyComponent test=\"pof pof\">",
    "type": "openTag",
    "tagName": "MyComponent",
    "startsAt": 416,
    "endsAt": 444,
    "properties": {
      "test": "pof pof"
    }
  },
  {
    "type": "raw",
    "value": "here ?",
    "startsAt": 444,
    "endsAt": 450
  },
  {
    "type": "raw",
    "value": " ",
    "startsAt": 329,
    "endsAt": 330
  },
  {
    "value": "<Test>",
    "type": "openTag",
    "tagName": "Test",
    "startsAt": 330,
    "endsAt": 336,
    "properties": {}
  },
  {
    "type": "raw",
    "value": "another",
    "startsAt": 336,
    "endsAt": 343
  },
  {
    "type": "raw",
    "value": " ",
    "startsAt": 350,
    "endsAt": 351
  },
  {
    "value": "<Test>",
    "type": "openTag",
    "tagName": "Test",
    "startsAt": 351,
    "endsAt": 357,
    "properties": {}
  },
  {
    "type": "raw",
    "value": "another",
    "startsAt": 357,
    "endsAt": 364
  },
  {
    "type": "raw",
    "value": " let's continue until it break ",
    "startsAt": 464,
    "endsAt": 495
  },
  {
    "value": "<Test>",
    "type": "openTag",
    "tagName": "Test",
    "startsAt": 495,
    "endsAt": 501,
    "properties": {}
  },
  {
    "type": "raw",
    "value": "is it breaking ?",
    "startsAt": 501,
    "endsAt": 517
  },
  {
    "value": "</Test>",
    "type": "closingTag",
    "tagName": "Test",
    "startsAt": 517,
    "endsAt": 524
  },
  {
    "type": "raw",
    "value": ".\n  \n  Let's try to continue",
    "startsAt": 524,
    "endsAt": 552
  }
]
```

**Comment by pbellon** [comment]
Sorting solved my issue. I'm making a pull-request.

**Comment by fazouane-marouane** [comment]
Nice catch & fix! I merged your PR and published a new version. 🔥
